### ISSUE TITLE
path_to_wd not found

### ISSUE THREAD

**Issue by MihaelN** [srfdata/2017-10-instagram-influencers#1]
```
Loading required package: checkpoint

checkpoint: Part of the Reproducible R Toolkit from Microsoft
https://mran.microsoft.com/documents/rro/reproducibility/
Error in path.expand(path) : object 'path_to_wd' not found
In addition: Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘checkpoint’
2: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘devtools’
3: Username parameter is deprecated. Please use RevolutionAnalytics/checkpoint 

```

I got stuck here and cant procede, seems like `path_to_wd` is not found, what does it mean?

Edit;

Sorry, forgot to mention this was run on R version 3.4.3 on Windows 10 x64

**Comment by grssnbchr** [comment]
If `path_to_wd` is not found this is most likely due to the fact that you didn't alter the pre-specified working directory:

```
# Set working directory here!
path_to_wd <- switch(EXPR = system2("whoami", stdout = TRUE),
                     "srfdata" = "~/SRF/Projekte/2017-10-instagram-influencers/analysis/",
                     NULL)
# nolint end
if ( is.null(path_to_wd) ) {
  stop("No working directory specified for current user")
} else {
  setwd(path_to_wd)
}
```

You should alter `srfdata` to your username (get it with the `whoami` command in the shell on a Unix system) and then specify the location of your project folder after the `=`. 

This is a bit of a nuisance, sorry. In newer versions of our reproducible R template, the working directory is set automatically.

Does this resolve the issue?

**Comment by MihaelN** [comment]
This is where issue lies but it is not a solution, windows terminal does not support `whoami` command. 

However, I solved this by overwriting this value with string containing full path to my working directory. Thank you.

**Comment by grssnbchr** [comment]
Absolutely, you can also skip the `switch` expression (which we introduced a while ago to easily switch between the machines of different co-workers) and overwrite `path_to_wd` directly.
